# Generated by Django 3.1.2 on 2020-10-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0003_auto_20201004_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='img',
            field=models.ImageField(default=2, upload_to='', verbose_name='Фотография'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartphone',
            name='img',
            field=models.ImageField(default=2, upload_to='', verbose_name='Фотография'),
            preserve_default=False,
        ),
    ]
