# Generated by Django 3.1.2 on 2020-10-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0004_auto_20201004_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='display_res',
            field=models.CharField(default=0, max_length=10, verbose_name='Разрешение экрана'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartphone',
            name='matrix_type',
            field=models.CharField(default=0, max_length=40, verbose_name='Тип матрицы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartphone',
            name='memory',
            field=models.CharField(default=0, max_length=10, verbose_name="Встроеная пам'ять"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartphone',
            name='ram',
            field=models.CharField(default=0, max_length=10, verbose_name="Оперативная пам'ять"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartphone',
            name='scr_diagon',
            field=models.FloatField(default=0, verbose_name='Диагональ экрана'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartphone',
            name='scr_material',
            field=models.CharField(default=0, max_length=40, verbose_name='Материал экрана'),
            preserve_default=False,
        ),
    ]
