# Generated by Django 3.1.2 on 2020-10-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0005_auto_20201004_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='os',
            field=models.CharField(default=0, max_length=20, verbose_name='Операционная система'),
            preserve_default=False,
        ),
    ]
