# Generated by Django 3.1.2 on 2020-10-04 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0006_smartphone_os'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartphone',
            old_name='scr_diagon',
            new_name='scr_diagonal',
        ),
    ]
