# Generated by Django 3.1.2 on 2020-10-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0008_auto_20201009_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=40, verbose_name='Автор')),
                ('comment', models.TextField(max_length=2000, verbose_name='Комментарий')),
                ('advantages', models.TextField(max_length=500, verbose_name='Достоинства')),
                ('disadvantages', models.TextField(max_length=500, verbose_name='Недостатки')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AddField(
            model_name='laptop',
            name='description',
            field=models.TextField(default=1, max_length=1000, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartphone',
            name='description',
            field=models.TextField(default=1, max_length=1000, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
