# Generated by Django 3.1.2 on 2020-10-18 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0009_auto_20201018_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('country', models.CharField(max_length=40, verbose_name='Страна')),
                ('phone_number', models.CharField(max_length=40, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
            },
        ),
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.CreateModel(
            name='SmartphoneReview',
            fields=[
                ('review_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myshop.review')),
                ('smartphone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myshop.smartphone')),
            ],
            options={
                'verbose_name': 'Отзыв на смартфон',
                'verbose_name_plural': 'Отзывы на смартфоны',
            },
            bases=('myshop.review',),
        ),
        migrations.CreateModel(
            name='LaptopReview',
            fields=[
                ('review_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myshop.review')),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myshop.laptop')),
            ],
            options={
                'verbose_name': 'Отзыв на ноутбук',
                'verbose_name_plural': 'Отзывы на ноутбуки',
            },
            bases=('myshop.review',),
        ),
    ]
