# Generated by Django 3.1.2 on 2020-12-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0012_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='login',
            field=models.CharField(default=1, max_length=40, verbose_name='Логин'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.IntegerField(default=1, max_length=40, verbose_name='Пароль'),
            preserve_default=False,
        ),
    ]
