# Generated by Django 3.1.2 on 2020-12-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0013_auto_20201204_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.IntegerField(verbose_name='Пароль'),
        ),
    ]
