# Generated by Django 3.1.2 on 2020-12-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0014_auto_20201204_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=40, verbose_name='Пароль'),
        ),
    ]
