# Generated by Django 3.1.2 on 2020-12-05 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0016_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='product_id',
            field=models.IntegerField(default=1, verbose_name='Id-продукта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basket',
            name='type_of_product',
            field=models.CharField(default=1, max_length=40, verbose_name='Тип продукта'),
            preserve_default=False,
        ),
    ]
