# Generated by Django 3.1.2 on 2020-12-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0017_auto_20201205_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='cnt',
            field=models.IntegerField(default=1, verbose_name='Кількість продукту'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basket',
            name='product_id',
            field=models.IntegerField(verbose_name='Id-продукту'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='type_of_product',
            field=models.CharField(max_length=40, verbose_name='Тип продукту'),
        ),
    ]
