# Generated by Django 3.1.2 on 2020-12-08 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0019_basket_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name': 'Кошик', 'verbose_name_plural': 'Кошики'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Покупець', 'verbose_name_plural': 'Покупці'},
        ),
        migrations.AlterModelOptions(
            name='laptopreview',
            options={'verbose_name': 'Відгук на ноутбук', 'verbose_name_plural': 'Відгуки на ноутбуки'},
        ),
        migrations.AlterModelOptions(
            name='smartphone',
            options={'verbose_name': 'Смартфон', 'verbose_name_plural': 'Смартфони'},
        ),
        migrations.AlterModelOptions(
            name='smartphonereview',
            options={'verbose_name': 'Відгук на смартфон', 'verbose_name_plural': 'Відгуки на смартфони'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(max_length=40, verbose_name='Країна'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=40, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=40, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='login',
            field=models.CharField(max_length=40, verbose_name='Логін'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=40, verbose_name='Номер телефону'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='battery_characteristics',
            field=models.CharField(max_length=50, verbose_name='Характеристики батареї'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='color',
            field=models.CharField(max_length=50, verbose_name='Колір'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='count_in_stock',
            field=models.IntegerField(verbose_name='Кількість на складі'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='country',
            field=models.CharField(max_length=50, verbose_name='Країна-виробник товару'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Опис товару'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='Фотографія'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Назва товару'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='network_adapters',
            field=models.CharField(max_length=50, verbose_name='Мережеві адаптери'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='price',
            field=models.IntegerField(verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='scr_diagonal',
            field=models.FloatField(max_length=10, verbose_name='Діагональ экрану'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='scr_refresh',
            field=models.CharField(max_length=50, verbose_name='Частота оновлення екрану'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='warranty',
            field=models.CharField(max_length=50, verbose_name='Гарантія'),
        ),
        migrations.AlterField(
            model_name='review',
            name='advantages',
            field=models.TextField(max_length=500, verbose_name='Переваги'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(max_length=2000, verbose_name='Коментар'),
        ),
        migrations.AlterField(
            model_name='review',
            name='disadvantages',
            field=models.TextField(max_length=500, verbose_name='Недоліки'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='color',
            field=models.CharField(max_length=50, verbose_name='Колір'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='count_in_stock',
            field=models.IntegerField(verbose_name='Кількість на складі'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='country',
            field=models.CharField(max_length=50, verbose_name='Країна-виробник товару'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Опис товару'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='display_res',
            field=models.CharField(max_length=50, verbose_name='Розширення экрану'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='Фотографія'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='matrix_type',
            field=models.CharField(max_length=40, verbose_name='Тип матриці'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='memory',
            field=models.CharField(max_length=10, verbose_name="Влаштована пам'ять"),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Назва товару'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='os',
            field=models.CharField(max_length=50, verbose_name='Операційна система'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='price',
            field=models.IntegerField(verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='ram',
            field=models.CharField(max_length=10, verbose_name="Оперативна пам'ять"),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='scr_diagonal',
            field=models.FloatField(verbose_name='Діагональ екрану'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='scr_material',
            field=models.CharField(max_length=50, verbose_name='Матеріал екрану'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='warranty',
            field=models.CharField(max_length=50, verbose_name='Гарантія'),
        ),
    ]
