# Generated by Django 3.1.2 on 2020-12-08 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0020_auto_20201208_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='money',
            field=models.IntegerField(default=0, verbose_name='Гроші'),
            preserve_default=False,
        ),
    ]
